"""
add created_at column to task and update taskstatus enum values to uppercase

Revision ID: 63554fd6d249
Revises: 828719163793
Create Date: 2025-07-03 12:15:07.092445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63554fd6d249'
down_revision: Union[str, Sequence[str], None] = '828719163793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'created_at')
    # ### end Alembic commands ###
